version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    dependencies:
      pre:
      - apt-get update; apt-get install make; apt-get install gcc
    steps:
      - checkout  
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: sudo apt-get update; sudo apt-get install gcc; sudo apt-get install make
      - run: make

