version: 2
jobs:
  build:
    docker:
      - image: gcc
    dependencies:
      pre:
      - sudo apt-get update; sudo apt-get install make; sudo apt-get install gcc
    steps:
      - checkout  
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: make

