version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install gcc;
    - sudo apt-get update; sudo apt-get install make
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: make

